package com.galaxy.taylor.model;

import com.galaxy.taylor.model.base.BaseClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify();
}
