package com.galaxy.taylor.model;

import com.galaxy.taylor.model.base.BaseRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Right extends BaseRight<Right> {
	public static final Right dao = new Right();
}
