package com.galaxy.taylor.model;

import com.galaxy.taylor.model.base.BaseUsertype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usertype extends BaseUsertype<Usertype> {
	public static final Usertype dao = new Usertype();
}
