package com.galaxy.taylor.model;

import com.galaxy.taylor.model.base.BaseUserRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRight extends BaseUserRight<UserRight> {
	public static final UserRight dao = new UserRight();
}
