package com.galaxy.taylor.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassify<M extends BaseClassify<M>> extends Model<M> implements IBean {

	public void setTypeId(java.lang.Integer typeId) {
		set("typeId", typeId);
	}

	public java.lang.Integer getTypeId() {
		return get("typeId");
	}

	public void setParentTypeId(java.lang.Integer parentTypeId) {
		set("parentTypeId", parentTypeId);
	}

	public java.lang.Integer getParentTypeId() {
		return get("parentTypeId");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
