package com.galaxy.taylor.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setCommentId(java.lang.Integer commentId) {
		set("commentId", commentId);
	}

	public java.lang.Integer getCommentId() {
		return get("commentId");
	}

	public void setBlogId(java.lang.Integer blogId) {
		set("blogId", blogId);
	}

	public java.lang.Integer getBlogId() {
		return get("blogId");
	}

	public void setCommentUserId(java.lang.Integer commentUserId) {
		set("commentUserId", commentUserId);
	}

	public java.lang.Integer getCommentUserId() {
		return get("commentUserId");
	}

	public void setCommentContent(java.lang.String commentContent) {
		set("commentContent", commentContent);
	}

	public java.lang.String getCommentContent() {
		return get("commentContent");
	}

	public void setCommentTime(java.util.Date commentTime) {
		set("commentTime", commentTime);
	}

	public java.util.Date getCommentTime() {
		return get("commentTime");
	}

}
