package com.galaxy.taylor.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRight<M extends BaseRight<M>> extends Model<M> implements IBean {

	public void setRightId(java.lang.Integer rightId) {
		set("rightId", rightId);
	}

	public java.lang.Integer getRightId() {
		return get("rightId");
	}

	public void setRightName(java.lang.String rightName) {
		set("rightName", rightName);
	}

	public java.lang.String getRightName() {
		return get("rightName");
	}

	public void setRightUrl(java.lang.String rightUrl) {
		set("rightUrl", rightUrl);
	}

	public java.lang.String getRightUrl() {
		return get("rightUrl");
	}

}
