package com.blogme.taylor.model;

import com.blogme.taylor.model.base.BaseUsertype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usertype extends BaseUsertype<Usertype> {
	public static final Usertype dao = new Usertype();
}
